#!/usr/bin/env node

/**
 * Build the small, controlled catalog used by the hackathon demo.
 *
 * The original H&M clothing sample is intentionally not read or written here. It remains the
 * source for clothing search and bundle demonstrations. The synthetic non-clothing fixtures use
 * the same Amazon-shaped envelope as the existing loader, with an additional structured_attributes
 * object so each relevance decision can be traced to an explicit fact.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(SCRIPT_DIR, "..");

// One representative image is deliberately shared by each synthetic product family. These are
// illustrative Amazon-image URLs retained from the source sample, not live merchant listings.
const IMAGE_URL_BY_FAMILY = {
  running_smartwatch: "https://m.media-amazon.com/images/I/51ajKKbi76L._AC_UL1000_.jpg",
  running_wireless_earbuds: "https://m.media-amazon.com/images/I/6182myBMxuL._AC_SL1500_.jpg",
  earbud_charging_case: "https://m.media-amazon.com/images/I/81wW5sRA+jS._AC_SL1500_.jpg",
  portable_running_power_bank: "https://m.media-amazon.com/images/I/81hAcNitfKL._AC_SL1500_.jpg",
  outdoor_security_camera: "https://m.media-amazon.com/images/I/51ygkj-cYwL._AC_SL1000_.jpg",
  camera_micro_sd: "https://m.media-amazon.com/images/I/61jajvgWBzL._AC_SL1000_.jpg",
  camera_mount: "https://m.media-amazon.com/images/I/314+6fI-J5L._AC_.jpg",
  oily_skin_cleanser: "https://m.media-amazon.com/images/I/71n%2BJv2f1aL._SL1500_.jpg",
  oily_skin_toner: "https://m.media-amazon.com/images/I/31nOZ6HiDTL.jpg",
  oily_skin_moisturizer: "https://m.media-amazon.com/images/I/71F7VzOU-gL._SL1500_.jpg",
};

// The generic bundle engine reads these target keys and roles from the data. New product families
// can participate by declaring metadata here rather than requiring an engine code branch.
const BUNDLE_PROFILE_BY_FAMILY = {
  running_smartwatch: { targets: ["running_audio"], compatibility_tags: ["running", "casual_workout"] },
  running_wireless_earbuds: {
    roles: ["running_audio"],
    targets: ["earbud_charging_case", "portable_running_power"],
    compatibility_tags: ["running", "casual_workout"],
  },
  earbud_charging_case: { roles: ["earbud_charging_case"], compatibility_tags: ["running", "casual_workout"] },
  portable_running_power_bank: { roles: ["portable_running_power"], compatibility_tags: ["running", "casual_workout"] },
  outdoor_security_camera: { targets: ["camera_storage", "camera_mount"], compatibility_tags: ["outdoor_security"] },
  camera_micro_sd: { roles: ["camera_storage"], compatibility_tags: ["outdoor_security"] },
  camera_mount: { roles: ["camera_mount"], compatibility_tags: ["outdoor_security"] },
  oily_skin_cleanser: {
    targets: ["post_cleanse_toner", "lightweight_moisturizer"],
    compatibility_tags: ["oily", "acne_prone"],
  },
  oily_skin_toner: {
    roles: ["post_cleanse_toner"],
    targets: ["lightweight_moisturizer"],
    compatibility_tags: ["oily", "acne_prone"],
  },
  oily_skin_moisturizer: { roles: ["lightweight_moisturizer"], compatibility_tags: ["oily", "acne_prone"] },
};

function bundleMetadata(productFamily, variant) {
  return {
    ...(BUNDLE_PROFILE_BY_FAMILY[productFamily] ?? {}),
    // Near-miss variants remain in retrieval tests but never become automatic upsells.
    offer_eligible: /^(exact_match|valid_lower_resolution_match|complementary_add_on)$/.test(variant),
    priority: variant === "exact_match" ? 100 : variant === "valid_lower_resolution_match" ? 80 : 90,
  };
}

const baseRecord = ({
  id,
  categoryPath,
  catalogGroup,
  productFamily,
  variant,
  title,
  priceUsd,
  features,
  details,
  structuredAttributes,
  imageUrl = IMAGE_URL_BY_FAMILY[productFamily] ?? null,
}) => ({
  id,
  source: "Synthetic demo fixture derived from the Amazon catalog schema",
  main_category: categoryPath[0],
  category_path: categoryPath,
  catalog_group: catalogGroup,
  product_family: productFamily,
  variant_key: variant,
  title,
  brand_or_store: "MatchProof Demo",
  price_usd: priceUsd,
  average_rating: 4.5,
  rating_count: 120,
  features,
  description: [
    `Controlled ${productFamily} demo fixture. Variant: ${variant}.`,
    "All retrieval-critical facts are stated explicitly in features and structured_attributes.",
  ],
  details,
  structured_attributes: {
    schema_version: 1,
    product_family: productFamily,
    variant,
    bundling: bundleMetadata(productFamily, variant),
    ...structuredAttributes,
  },
  image_url: imageUrl,
});

const electronics = [
  baseRecord({
    id: "DEMO-WATCH-EXACT",
    categoryPath: ["Electronics", "Wearable Technology", "Smartwatches"],
    catalogGroup: "mobile_accessories",
    productFamily: "running_smartwatch",
    variant: "exact_match",
    title: "Aurelia RunDress GPS Smartwatch",
    priceUsd: 249,
    features: [
      "Built-in GPS records live running pace, distance, and route without a phone.",
      "Optical heart-rate sensor provides continuous heart-rate tracking during workouts.",
      "5ATM water resistance and an included silicone strap support running and casual workouts.",
      "Polished stainless-steel round case and included leather strap are suitable for formal dates.",
    ],
    details: { FormFactor: "Round smartwatch", WaterResistance: "5ATM", IncludedStraps: ["silicone", "leather"] },
    structuredAttributes: {
      item_type: "smartwatch",
      use_cases: ["running", "casual_workout", "formal_date"],
      fitness: { built_in_gps: true, gps_pace_tracking: true, continuous_heart_rate_tracking: true },
      workout: { running_suitable: true },
      durability: { water_resistance: "5ATM" },
      style: { formal_suitable: true, case_material: "stainless steel", strap_options: ["silicone", "leather"] },
    },
  }),
  baseRecord({
    id: "DEMO-WATCH-SPORT",
    categoryPath: ["Electronics", "Wearable Technology", "Smartwatches"],
    catalogGroup: "mobile_accessories",
    productFamily: "running_smartwatch",
    variant: "missing_preferred_formal_style",
    title: "Aurelia RunSport GPS Smartwatch",
    priceUsd: 199,
    features: [
      "Built-in GPS records live running pace, distance, and route without a phone.",
      "Optical heart-rate sensor provides continuous heart-rate tracking during workouts.",
      "5ATM water resistance and a secure silicone strap support running and casual workouts.",
      "No formal styling; the rugged polymer case and neon sport strap are intended for exercise only.",
    ],
    details: { FormFactor: "Round smartwatch", WaterResistance: "5ATM", IncludedStraps: ["neon silicone"] },
    structuredAttributes: {
      item_type: "smartwatch",
      use_cases: ["running", "casual_workout"],
      fitness: { built_in_gps: true, gps_pace_tracking: true, continuous_heart_rate_tracking: true },
      workout: { running_suitable: true },
      durability: { water_resistance: "5ATM" },
      style: { formal_suitable: false, case_material: "polymer", strap_options: ["neon silicone"] },
    },
  }),
  baseRecord({
    id: "DEMO-WATCH-NO-GPS",
    categoryPath: ["Electronics", "Wearable Technology", "Smartwatches"],
    catalogGroup: "mobile_accessories",
    productFamily: "running_smartwatch",
    variant: "missing_mandatory_gps",
    title: "Aurelia DressHR Smartwatch",
    priceUsd: 229,
    features: [
      "No built-in GPS and no GPS pace tracking; outdoor pace requires a connected phone.",
      "Optical heart-rate sensor provides continuous heart-rate tracking during workouts.",
      "Polished stainless-steel round case and leather strap are suitable for formal dates.",
      "3ATM splash resistance supports daily wear but is not intended for swimming.",
    ],
    details: { FormFactor: "Round smartwatch", WaterResistance: "3ATM", IncludedStraps: ["leather"] },
    structuredAttributes: {
      item_type: "smartwatch",
      use_cases: ["casual_workout", "formal_date"],
      fitness: { built_in_gps: false, gps_pace_tracking: false, continuous_heart_rate_tracking: true },
      workout: { running_suitable: true },
      durability: { water_resistance: "3ATM" },
      style: { formal_suitable: true, case_material: "stainless steel", strap_options: ["leather"] },
    },
  }),
  baseRecord({
    id: "DEMO-WATCH-NO-HR",
    categoryPath: ["Electronics", "Wearable Technology", "Smartwatches"],
    catalogGroup: "mobile_accessories",
    productFamily: "running_smartwatch",
    variant: "missing_mandatory_heart_rate",
    title: "Aurelia DressGPS Smartwatch",
    priceUsd: 219,
    features: [
      "Built-in GPS records live running pace, distance, and route without a phone.",
      "No heart-rate sensor and no heart-rate tracking.",
      "Polished stainless-steel round case and leather strap are suitable for formal dates.",
      "5ATM water resistance supports running in wet weather.",
    ],
    details: { FormFactor: "Round smartwatch", WaterResistance: "5ATM", IncludedStraps: ["leather"] },
    structuredAttributes: {
      item_type: "smartwatch",
      use_cases: ["running", "formal_date"],
      fitness: { built_in_gps: true, gps_pace_tracking: true, continuous_heart_rate_tracking: false },
      workout: { running_suitable: true },
      durability: { water_resistance: "5ATM" },
      style: { formal_suitable: true, case_material: "stainless steel", strap_options: ["leather"] },
    },
  }),
  baseRecord({
    id: "DEMO-BUDS-EXACT",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Headphones & Earbuds", "Earbud Headphones"],
    catalogGroup: "audio",
    productFamily: "running_wireless_earbuds",
    variant: "exact_match",
    title: "Tempo RunConnect Multipoint Wireless Earbuds",
    priceUsd: 129,
    features: [
      "Bluetooth 5.3 fast pairing and one-second automatic reconnection.",
      "True multipoint connection keeps two devices connected simultaneously and switches between them.",
      "IPX5 sweat resistance and stabilizing ear fins provide a secure fit for running and casual workouts.",
      "Eight hours of playback per charge with a compact USB-C charging case.",
    ],
    details: { FormFactor: "In-ear true wireless earbuds", BluetoothVersion: "5.3", WaterResistance: "IPX5" },
    structuredAttributes: {
      item_type: "wireless_earbuds",
      use_cases: ["running", "casual_workout"],
      connectivity: { fast_pairing: true, reconnect_seconds: 1, multipoint: true, simultaneous_devices: 2 },
      workout: { sweat_resistant: true, water_resistance: "IPX5", secure_fit: true, ear_fins: true },
    },
  }),
  baseRecord({
    id: "DEMO-BUDS-NO-MULTIPOINT",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Headphones & Earbuds", "Earbud Headphones"],
    catalogGroup: "audio",
    productFamily: "running_wireless_earbuds",
    variant: "missing_mandatory_multipoint",
    title: "Tempo RunFast Single-Device Wireless Earbuds",
    priceUsd: 99,
    features: [
      "Bluetooth 5.3 fast pairing and one-second automatic reconnection.",
      "No multipoint and no multi-device connection; only one device can be connected at a time.",
      "IPX5 sweat resistance and stabilizing ear fins provide a secure fit for running and casual workouts.",
      "Eight hours of playback per charge with a compact USB-C charging case.",
    ],
    details: { FormFactor: "In-ear true wireless earbuds", BluetoothVersion: "5.3", WaterResistance: "IPX5" },
    structuredAttributes: {
      item_type: "wireless_earbuds",
      use_cases: ["running", "casual_workout"],
      connectivity: { fast_pairing: true, reconnect_seconds: 1, multipoint: false, simultaneous_devices: 1 },
      workout: { sweat_resistant: true, water_resistance: "IPX5", secure_fit: true, ear_fins: true },
    },
  }),
  baseRecord({
    id: "DEMO-BUDS-NO-WORKOUT",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Headphones & Earbuds", "Earbud Headphones"],
    catalogGroup: "audio",
    productFamily: "running_wireless_earbuds",
    variant: "missing_mandatory_workout_fit",
    title: "Tempo MultiConnect Office Wireless Earbuds",
    priceUsd: 119,
    features: [
      "Bluetooth 5.3 fast pairing and one-second automatic reconnection.",
      "True multipoint connection keeps two devices connected simultaneously and switches between them.",
      "No sweat resistance, no water-resistance rating, and no secure workout fit; intended for desk and commuting use.",
      "Nine hours of playback per charge with a compact USB-C charging case.",
    ],
    details: { FormFactor: "Open-fit true wireless earbuds", BluetoothVersion: "5.3", WaterResistance: "None" },
    structuredAttributes: {
      item_type: "wireless_earbuds",
      use_cases: ["office", "commuting"],
      connectivity: { fast_pairing: true, reconnect_seconds: 1, multipoint: true, simultaneous_devices: 2 },
      workout: { sweat_resistant: false, water_resistance: null, secure_fit: false, ear_fins: false },
    },
  }),
  baseRecord({
    id: "DEMO-BUDS-LEGACY",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Headphones & Earbuds", "Earbud Headphones"],
    catalogGroup: "audio",
    productFamily: "running_wireless_earbuds",
    variant: "missing_mandatory_connection_features",
    title: "Tempo SportBuds Legacy Wireless Earbuds",
    priceUsd: 69,
    features: [
      "Slow manual Bluetooth pairing with approximately eight-second reconnection.",
      "No multipoint and no multi-device connection; only one device can be connected at a time.",
      "IPX7 sweat resistance and stabilizing ear hooks provide a secure fit for running and casual workouts.",
      "Six hours of playback per charge with a Micro-USB charging case.",
    ],
    details: { FormFactor: "In-ear true wireless earbuds", BluetoothVersion: "5.0", WaterResistance: "IPX7" },
    structuredAttributes: {
      item_type: "wireless_earbuds",
      use_cases: ["running", "casual_workout"],
      connectivity: { fast_pairing: false, reconnect_seconds: 8, multipoint: false, simultaneous_devices: 1 },
      workout: { sweat_resistant: true, water_resistance: "IPX7", secure_fit: true, ear_fins: true },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-EXACT",
    categoryPath: ["Electronics", "Camera & Photo", "Video Surveillance", "Security Cameras"],
    catalogGroup: "camera_smart_home",
    productFamily: "outdoor_security_camera",
    variant: "exact_match",
    title: "Sentinel Outdoor Security Camera with Night Vision and Local Storage",
    priceUsd: 149,
    features: [
      "2K outdoor security camera with infrared color night vision.",
      "Local microSD storage works without a paid cloud subscription.",
      "IP66 weatherproof housing supports year-round outdoor installation.",
      "Dual-band Wi-Fi and motion alerts provide fast remote monitoring.",
    ],
    details: { Resolution: "2K", WaterResistance: "IP66", Storage: "microSD up to 256GB" },
    structuredAttributes: {
      item_type: "security_camera",
      use_cases: ["outdoor_security", "night_monitoring"],
      imaging: { resolution: "2K", night_vision: true },
      storage: { local_storage: true, medium: "microSD", cloud_subscription_required: false },
      installation: { outdoor_suitable: true, weather_resistance: "IP66" },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-NO-LOCAL",
    categoryPath: ["Electronics", "Camera & Photo", "Video Surveillance", "Security Cameras"],
    catalogGroup: "camera_smart_home",
    productFamily: "outdoor_security_camera",
    variant: "missing_mandatory_local_storage",
    title: "Sentinel Outdoor Cloud Security Camera",
    priceUsd: 129,
    features: [
      "2K outdoor security camera with infrared color night vision.",
      "No local storage; recording requires a paid cloud subscription.",
      "IP66 weatherproof housing supports year-round outdoor installation.",
      "Dual-band Wi-Fi and motion alerts provide fast remote monitoring.",
    ],
    details: { Resolution: "2K", WaterResistance: "IP66", Storage: "Paid cloud only" },
    structuredAttributes: {
      item_type: "security_camera",
      use_cases: ["outdoor_security", "night_monitoring"],
      imaging: { resolution: "2K", night_vision: true },
      storage: { local_storage: false, medium: "cloud", cloud_subscription_required: true },
      installation: { outdoor_suitable: true, weather_resistance: "IP66" },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-INDOOR",
    categoryPath: ["Electronics", "Camera & Photo", "Video Surveillance", "Security Cameras"],
    catalogGroup: "camera_smart_home",
    productFamily: "outdoor_security_camera",
    variant: "missing_mandatory_outdoor_rating",
    title: "Sentinel Indoor Security Camera with Local Storage",
    priceUsd: 89,
    features: [
      "2K indoor security camera with infrared night vision.",
      "Local microSD storage works without a paid cloud subscription.",
      "No weather resistance and no outdoor suitability; designed for dry indoor rooms only.",
      "Dual-band Wi-Fi and motion alerts provide fast remote monitoring.",
    ],
    details: { Resolution: "2K", WaterResistance: "None", Storage: "microSD up to 256GB" },
    structuredAttributes: {
      item_type: "security_camera",
      use_cases: ["indoor_security", "night_monitoring"],
      imaging: { resolution: "2K", night_vision: true },
      storage: { local_storage: true, medium: "microSD", cloud_subscription_required: false },
      installation: { outdoor_suitable: false, weather_resistance: null },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-NO-NIGHT",
    categoryPath: ["Electronics", "Camera & Photo", "Video Surveillance", "Security Cameras"],
    catalogGroup: "camera_smart_home",
    productFamily: "outdoor_security_camera",
    variant: "missing_mandatory_night_vision",
    title: "Sentinel Daylight Outdoor Security Camera with Local Storage",
    priceUsd: 99,
    features: [
      "2K outdoor security camera for daylight monitoring only; no night vision.",
      "Local microSD storage works without a paid cloud subscription.",
      "IP66 weatherproof housing supports year-round outdoor installation.",
      "Dual-band Wi-Fi and motion alerts provide fast remote monitoring.",
    ],
    details: { Resolution: "2K", WaterResistance: "IP66", Storage: "microSD up to 256GB" },
    structuredAttributes: {
      item_type: "security_camera",
      use_cases: ["outdoor_security", "daylight_monitoring"],
      imaging: { resolution: "2K", night_vision: false },
      storage: { local_storage: true, medium: "microSD", cloud_subscription_required: false },
      installation: { outdoor_suitable: true, weather_resistance: "IP66" },
    },
  }),
  baseRecord({
    id: "DEMO-WATCH-NO-PACE",
    categoryPath: ["Electronics", "Wearable Technology", "Smartwatches"],
    catalogGroup: "mobile_accessories",
    productFamily: "running_smartwatch",
    variant: "gps_without_pace_tracking",
    title: "Aurelia MapGPS Heart-Rate Smartwatch",
    priceUsd: 209,
    features: [
      "Built-in GPS supports maps and location recording, but no GPS pace tracking is available.",
      "Optical heart-rate sensor provides continuous heart-rate tracking during workouts.",
      "5ATM water resistance supports running in wet weather.",
      "Polished round case and leather strap are suitable for formal dates.",
    ],
    details: { FormFactor: "Round smartwatch", WaterResistance: "5ATM", IncludedStraps: ["leather"] },
    structuredAttributes: {
      item_type: "smartwatch",
      use_cases: ["location_tracking", "casual_workout", "formal_date"],
      fitness: { built_in_gps: true, gps_pace_tracking: false, continuous_heart_rate_tracking: true },
      workout: { running_suitable: true },
      style: { formal_suitable: true, case_material: "stainless steel" },
    },
  }),
  baseRecord({
    id: "DEMO-WATCH-NOT-RUNNING",
    categoryPath: ["Electronics", "Wearable Technology", "Smartwatches"],
    catalogGroup: "mobile_accessories",
    productFamily: "running_smartwatch",
    variant: "missing_mandatory_running_suitability",
    title: "Aurelia Delicate GPS Heart-Rate Smartwatch",
    priceUsd: 239,
    features: [
      "Built-in GPS records location and pace, and an optical sensor records continuous heart rate.",
      "No running suitability: the delicate clasp is not secure for workouts and the case has no water resistance.",
      "Polished slim case and leather strap are suitable for formal dates.",
      "Designed for daily wellness and light walking rather than running or casual workouts.",
    ],
    details: { FormFactor: "Slim smartwatch", WaterResistance: "None", IncludedStraps: ["delicate leather"] },
    structuredAttributes: {
      item_type: "smartwatch",
      use_cases: ["walking", "formal_date"],
      fitness: { built_in_gps: true, gps_pace_tracking: true, continuous_heart_rate_tracking: true },
      workout: { running_suitable: false },
      style: { formal_suitable: true, case_material: "stainless steel" },
    },
  }),
  baseRecord({
    id: "DEMO-WATCH-FITNESS-BAND",
    categoryPath: ["Electronics", "Wearable Technology", "Fitness Trackers"],
    catalogGroup: "mobile_accessories",
    productFamily: "running_smartwatch",
    variant: "wrong_item_type_fitness_band",
    title: "Aurelia PaceBand GPS Fitness Tracker",
    priceUsd: 129,
    features: [
      "Fitness tracker band with built-in GPS pace tracking and continuous optical heart-rate tracking.",
      "5ATM water resistance and a silicone band support running and casual workouts.",
      "Not a smartwatch; the narrow fitness band has no apps, messaging, or watch-style interface.",
      "No formal styling; designed for sport use only.",
    ],
    details: { FormFactor: "Fitness tracker band", WaterResistance: "5ATM" },
    structuredAttributes: {
      item_type: "fitness_tracker",
      use_cases: ["running", "casual_workout"],
      fitness: { built_in_gps: true, gps_pace_tracking: true, continuous_heart_rate_tracking: true },
      workout: { running_suitable: true },
      style: { formal_suitable: false },
    },
  }),
  baseRecord({
    id: "DEMO-WATCH-ANALOG",
    categoryPath: ["Clothing, Shoes & Jewelry", "Watches", "Wrist Watches"],
    catalogGroup: "mobile_accessories",
    productFamily: "running_smartwatch",
    variant: "wrong_item_type_analog_watch",
    title: "Aurelia Classic Analog Dress Watch",
    priceUsd: 189,
    features: [
      "Analog dress watch with no smart features, no GPS, no pace tracking, and no heart-rate sensor.",
      "Not suitable for workout tracking or running metrics.",
      "Polished stainless-steel case and leather strap are suitable for formal dates.",
      "Traditional quartz movement with a date window.",
    ],
    details: { FormFactor: "Analog wrist watch", WaterResistance: "3ATM" },
    structuredAttributes: {
      item_type: "analog_watch",
      use_cases: ["formal_date", "timekeeping"],
      fitness: { built_in_gps: false, gps_pace_tracking: false, continuous_heart_rate_tracking: false },
      workout: { running_suitable: false },
      style: { formal_suitable: true },
    },
  }),
  baseRecord({
    id: "DEMO-BUDS-NO-FAST",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Headphones & Earbuds", "Earbud Headphones"],
    catalogGroup: "audio",
    productFamily: "running_wireless_earbuds",
    variant: "missing_mandatory_fast_connection",
    title: "Tempo MultiSport Slow-Pair Wireless Earbuds",
    priceUsd: 109,
    features: [
      "Slow manual Bluetooth pairing with approximately eight-second reconnection.",
      "True multipoint connection keeps two devices connected simultaneously.",
      "IPX5 sweat resistance and stabilizing ear fins provide a secure running fit.",
      "Eight hours of playback per charge.",
    ],
    details: { FormFactor: "In-ear true wireless earbuds", BluetoothVersion: "5.1", WaterResistance: "IPX5" },
    structuredAttributes: {
      item_type: "wireless_earbuds",
      use_cases: ["running", "casual_workout"],
      connectivity: { fast_pairing: false, reconnect_seconds: 8, multipoint: true, simultaneous_devices: 2 },
      workout: { sweat_resistant: true, water_resistance: "IPX5", secure_fit: true },
    },
  }),
  baseRecord({
    id: "DEMO-BUDS-LOOSE-FIT",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Headphones & Earbuds", "Earbud Headphones"],
    catalogGroup: "audio",
    productFamily: "running_wireless_earbuds",
    variant: "missing_mandatory_secure_fit",
    title: "Tempo AirConnect Loose-Fit Wireless Earbuds",
    priceUsd: 119,
    features: [
      "Bluetooth 5.3 fast pairing and one-second automatic reconnection.",
      "True multipoint connection keeps two devices connected simultaneously.",
      "IPX5 sweat resistance, but no secure workout fit; the loose open-fit design may fall out while running.",
      "Designed for casual listening rather than exercise.",
    ],
    details: { FormFactor: "Loose open-fit wireless earbuds", BluetoothVersion: "5.3", WaterResistance: "IPX5" },
    structuredAttributes: {
      item_type: "wireless_earbuds",
      use_cases: ["casual_listening"],
      connectivity: { fast_pairing: true, reconnect_seconds: 1, multipoint: true, simultaneous_devices: 2 },
      workout: { sweat_resistant: true, water_resistance: "IPX5", secure_fit: false },
    },
  }),
  baseRecord({
    id: "DEMO-BUDS-HEADSET",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Headsets"],
    catalogGroup: "audio",
    productFamily: "running_wireless_earbuds",
    variant: "wrong_item_type_headset",
    title: "Tempo OfficeConnect Wireless Over-Ear Headset",
    priceUsd: 149,
    features: [
      "Wireless over-ear headset with fast pairing and multipoint connection for two devices.",
      "Not wireless earbuds; full-size ear cups and boom microphone are intended for office calls.",
      "No sweat resistance and no secure running fit.",
      "Twenty hours of call time per charge.",
    ],
    details: { FormFactor: "Over-ear headset", BluetoothVersion: "5.3", WaterResistance: "None" },
    structuredAttributes: {
      item_type: "wireless_headset",
      use_cases: ["office_calls"],
      connectivity: { fast_pairing: true, reconnect_seconds: 1, multipoint: true, simultaneous_devices: 2 },
      workout: { sweat_resistant: false, water_resistance: null, secure_fit: false },
    },
  }),
  baseRecord({
    id: "DEMO-BUDS-WIRED",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Headphones & Earbuds", "Earbud Headphones"],
    catalogGroup: "audio",
    productFamily: "running_wireless_earbuds",
    variant: "wrong_connectivity_wired",
    title: "Tempo SecureFit Wired Sport Earbuds",
    priceUsd: 29,
    features: [
      "Wired 3.5mm sport earbuds with no Bluetooth, no fast pairing, and no wireless reconnection.",
      "No multipoint or multi-device wireless connection.",
      "IPX5 sweat resistance and ear hooks provide a secure running fit.",
      "Inline remote and microphone for calls.",
    ],
    details: { FormFactor: "Wired in-ear earbuds", Connectivity: "3.5mm cable", WaterResistance: "IPX5" },
    structuredAttributes: {
      item_type: "wired_earbuds",
      use_cases: ["running", "casual_workout"],
      connectivity: { fast_pairing: false, reconnect_seconds: null, multipoint: false, simultaneous_devices: 1 },
      workout: { sweat_resistant: true, water_resistance: "IPX5", secure_fit: true },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-EXACT-1080",
    categoryPath: ["Electronics", "Camera & Photo", "Video Surveillance", "Security Cameras"],
    catalogGroup: "camera_smart_home",
    productFamily: "outdoor_security_camera",
    variant: "valid_lower_resolution_match",
    title: "Sentinel Essential Outdoor Security Camera with Local Storage",
    priceUsd: 99,
    features: [
      "1080p outdoor security camera with infrared night vision.",
      "Local microSD storage works without a paid cloud subscription.",
      "IP65 weather-resistant housing supports outdoor installation.",
      "Wi-Fi motion alerts provide remote monitoring.",
    ],
    details: { Resolution: "1080p", WaterResistance: "IP65", Storage: "microSD up to 128GB" },
    structuredAttributes: {
      item_type: "security_camera",
      use_cases: ["outdoor_security", "night_monitoring"],
      imaging: { resolution: "1080p", night_vision: true },
      storage: { local_storage: true, medium: "microSD", cloud_subscription_required: false },
      installation: { outdoor_suitable: true, weather_resistance: "IP65" },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-NO-WEATHER",
    categoryPath: ["Electronics", "Camera & Photo", "Video Surveillance", "Security Cameras"],
    catalogGroup: "camera_smart_home",
    productFamily: "outdoor_security_camera",
    variant: "missing_mandatory_weather_resistance",
    title: "Sentinel Porch Security Camera with Local Storage",
    priceUsd: 109,
    features: [
      "2K security camera with infrared night vision and local microSD storage.",
      "No weather resistance; it must stay under a fully covered porch and cannot withstand rain.",
      "Not suitable for exposed outdoor installation.",
      "Wi-Fi motion alerts provide remote monitoring.",
    ],
    details: { Resolution: "2K", WaterResistance: "None", Storage: "microSD up to 256GB" },
    structuredAttributes: {
      item_type: "security_camera",
      use_cases: ["covered_porch_security", "night_monitoring"],
      imaging: { resolution: "2K", night_vision: true },
      storage: { local_storage: true, medium: "microSD", cloud_subscription_required: false },
      installation: { outdoor_suitable: false, weather_resistance: null },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-DOORBELL",
    categoryPath: ["Electronics", "Smart Home", "Video Doorbells"],
    catalogGroup: "camera_smart_home",
    productFamily: "outdoor_security_camera",
    variant: "wrong_item_type_video_doorbell",
    title: "Sentinel Video Doorbell with Night Vision and Local Storage",
    priceUsd: 139,
    features: [
      "Weather-resistant video doorbell with night vision and local microSD storage.",
      "Not a general outdoor security camera; designed only for doorbell replacement installation.",
      "IP65 housing withstands outdoor weather.",
      "Two-way audio and visitor alerts.",
    ],
    details: { Resolution: "2K", WaterResistance: "IP65", Storage: "microSD up to 128GB" },
    structuredAttributes: {
      item_type: "video_doorbell",
      use_cases: ["front_door_monitoring"],
      imaging: { resolution: "2K", night_vision: true },
      storage: { local_storage: true, medium: "microSD", cloud_subscription_required: false },
      installation: { outdoor_suitable: true, weather_resistance: "IP65" },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-MOUNT",
    categoryPath: ["Electronics", "Camera & Photo", "Video Surveillance", "Mounts"],
    catalogGroup: "camera_smart_home",
    productFamily: "outdoor_security_camera",
    variant: "wrong_item_type_accessory",
    title: "Sentinel Weatherproof Security Camera Wall Mount",
    priceUsd: 24,
    features: [
      "Wall-mount accessory for outdoor security cameras; camera is not included.",
      "No image sensor, no night vision, and no local storage.",
      "Weather-resistant aluminum mounting bracket.",
      "Compatible with Sentinel camera housings.",
    ],
    details: { ProductType: "Camera mount", Material: "Aluminum", CameraIncluded: false },
    structuredAttributes: {
      item_type: "camera_mount",
      use_cases: ["camera_installation"],
      imaging: { resolution: null, night_vision: false },
      storage: { local_storage: false, medium: null, cloud_subscription_required: false },
      installation: { outdoor_suitable: true, weather_resistance: "IP66" },
    },
  }),
  baseRecord({
    id: "DEMO-EARBUD-CASE",
    categoryPath: ["Electronics", "Headphones, Earbuds & Accessories", "Charging Cases"],
    catalogGroup: "charging_connectivity",
    productFamily: "earbud_charging_case",
    variant: "complementary_add_on",
    title: "Tempo PocketCharge Protective Earbud Charging Case",
    priceUsd: 35,
    features: [
      "USB-C charging case designed for Tempo wireless earbuds.",
      "Adds two full earbud recharges and protects the earbuds between runs.",
      "Compact water-resistant shell fits a running belt or jacket pocket.",
    ],
    details: { ProductType: "Earbud charging case", Connector: "USB-C", CompatibleFamily: "Tempo" },
    structuredAttributes: {
      item_type: "earbud_charging_case",
      use_cases: ["running", "casual_workout"],
      compatibility: { compatible_product_family: "running_wireless_earbuds" },
    },
  }),
  baseRecord({
    id: "DEMO-RUN-POWER",
    categoryPath: ["Electronics", "Portable Power", "Power Banks"],
    catalogGroup: "charging_connectivity",
    productFamily: "portable_running_power_bank",
    variant: "complementary_add_on",
    title: "Tempo RunCharge Compact USB-C Power Bank",
    priceUsd: 29,
    features: [
      "Lightweight 5,000mAh USB-C power bank for earbuds and phone charging on long runs.",
      "Pocket-sized, sweat-resistant shell with USB-C fast charging output.",
      "Includes a short USB-C cable for a compact workout kit.",
    ],
    details: { Capacity: "5000mAh", Connector: "USB-C", FastCharging: true },
    structuredAttributes: {
      item_type: "portable_power_bank",
      use_cases: ["running", "casual_workout", "travel"],
      charging: { connector: "USB-C", fast_charging: true },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-MICROSD",
    categoryPath: ["Electronics", "Camera & Photo", "Memory Cards"],
    catalogGroup: "storage",
    productFamily: "camera_micro_sd",
    variant: "complementary_add_on",
    title: "Sentinel Endurance 256GB microSD Card for Security Cameras",
    priceUsd: 32,
    features: [
      "256GB high-endurance microSD card for continuous local security-camera recording.",
      "Rated for outdoor temperature changes and repeated overwriting.",
      "Compatible with Sentinel cameras that support local microSD storage.",
    ],
    details: { Capacity: "256GB", CardType: "microSD", IntendedUse: "continuous security recording" },
    structuredAttributes: {
      item_type: "micro_sd_card",
      use_cases: ["outdoor_security", "local_camera_storage"],
      compatibility: { compatible_product_family: "outdoor_security_camera" },
    },
  }),
  baseRecord({
    id: "DEMO-CAMERA-MOUNT-ADDON",
    categoryPath: ["Electronics", "Camera & Photo", "Video Surveillance", "Mounts"],
    catalogGroup: "camera_accessories",
    productFamily: "camera_mount",
    variant: "complementary_add_on",
    title: "Sentinel Adjustable Outdoor Security Camera Mount",
    priceUsd: 24,
    features: [
      "Weatherproof adjustable wall mount for Sentinel outdoor security cameras.",
      "Allows a clear angle for driveway, porch, or side-gate monitoring.",
      "Camera sold separately; compatible with Sentinel outdoor camera housings.",
    ],
    details: { ProductType: "Security camera mount", WeatherResistance: "IP66", CompatibleFamily: "Sentinel" },
    structuredAttributes: {
      item_type: "security_camera_mount",
      use_cases: ["outdoor_security", "camera_installation"],
      compatibility: { compatible_product_family: "outdoor_security_camera" },
    },
  }),
];

const skincare = [
  baseRecord({
    id: "DEMO-CLEANSER-EXACT",
    categoryPath: ["Beauty & Personal Care", "Skin Care", "Face", "Cleansers"],
    catalogGroup: "cleanser",
    productFamily: "oily_skin_cleanser",
    variant: "exact_match",
    title: "ClearKind Fragrance-Free Gel Cleanser for Oily Skin",
    priceUsd: 18,
    features: [
      "Facial gel cleanser formulated for oily and acne-prone skin.",
      "Fragrance-free, essential-oil-free, and non-comedogenic formula.",
      "Gentle daily cleansing with niacinamide and zinc PCA.",
      "Budget-friendly price under $25.",
    ],
    details: { SkinType: ["Oily", "Acne-prone"], Form: "Gel", Fragrance: "Fragrance-free", VolumeMl: 150 },
    structuredAttributes: {
      item_type: "facial_cleanser",
      use_cases: ["daily_cleansing"],
      skin: { suitable_skin_types: ["oily", "acne_prone"], concerns: ["excess_oil", "blemishes"] },
      formula: { fragrance_free: true, non_comedogenic: true, texture: "gel" },
    },
  }),
  baseRecord({
    id: "DEMO-CLEANSER-FRAGRANCED",
    categoryPath: ["Beauty & Personal Care", "Skin Care", "Face", "Cleansers"],
    catalogGroup: "cleanser",
    productFamily: "oily_skin_cleanser",
    variant: "missing_preferred_fragrance_free",
    title: "ClearKind Citrus Gel Cleanser for Oily Skin",
    priceUsd: 16,
    features: [
      "Facial gel cleanser formulated for oily and acne-prone skin.",
      "Contains citrus fragrance and is not fragrance-free.",
      "Gentle daily cleansing with niacinamide and zinc PCA.",
      "Budget-friendly price under $25.",
    ],
    details: { SkinType: ["Oily", "Acne-prone"], Form: "Gel", Fragrance: "Citrus fragrance", VolumeMl: 150 },
    structuredAttributes: {
      item_type: "facial_cleanser",
      use_cases: ["daily_cleansing"],
      skin: { suitable_skin_types: ["oily", "acne_prone"], concerns: ["excess_oil", "blemishes"] },
      formula: { fragrance_free: false, non_comedogenic: true, texture: "gel" },
    },
  }),
  baseRecord({
    id: "DEMO-CLEANSER-DRY-SKIN",
    categoryPath: ["Beauty & Personal Care", "Skin Care", "Face", "Cleansers"],
    catalogGroup: "cleanser",
    productFamily: "oily_skin_cleanser",
    variant: "missing_mandatory_skin_type",
    title: "ClearKind Fragrance-Free Cream Cleanser for Dry Skin",
    priceUsd: 18,
    features: [
      "Facial cream cleanser formulated for dry skin; not suitable for oily or acne-prone skin.",
      "Fragrance-free, essential-oil-free, and non-comedogenic formula.",
      "Rich daily cleansing with squalane and ceramides.",
      "Budget-friendly price under $25.",
    ],
    details: { SkinType: ["Dry"], Form: "Cream", Fragrance: "Fragrance-free", VolumeMl: 150 },
    structuredAttributes: {
      item_type: "facial_cleanser",
      use_cases: ["daily_cleansing"],
      skin: { suitable_skin_types: ["dry"], concerns: ["dryness", "barrier_support"] },
      formula: { fragrance_free: true, non_comedogenic: true, texture: "cream" },
    },
  }),
  baseRecord({
    id: "DEMO-CLEANSER-OVER-BUDGET",
    categoryPath: ["Beauty & Personal Care", "Skin Care", "Face", "Cleansers"],
    catalogGroup: "cleanser",
    productFamily: "oily_skin_cleanser",
    variant: "missing_mandatory_budget",
    title: "ClearKind Premium Fragrance-Free Gel Cleanser for Oily Skin",
    priceUsd: 38,
    features: [
      "Facial gel cleanser formulated for oily and acne-prone skin.",
      "Fragrance-free, essential-oil-free, and non-comedogenic formula.",
      "Gentle daily cleansing with niacinamide and zinc PCA.",
      "Premium price over $25.",
    ],
    details: { SkinType: ["Oily", "Acne-prone"], Form: "Gel", Fragrance: "Fragrance-free", VolumeMl: 150 },
    structuredAttributes: {
      item_type: "facial_cleanser",
      use_cases: ["daily_cleansing"],
      skin: { suitable_skin_types: ["oily", "acne_prone"], concerns: ["excess_oil", "blemishes"] },
      formula: { fragrance_free: true, non_comedogenic: true, texture: "gel" },
    },
  }),
  baseRecord({
    id: "DEMO-CLEANSER-EXACT-FOAM",
    categoryPath: ["Beauty & Personal Care", "Skin Care", "Face", "Cleansers"],
    catalogGroup: "cleanser",
    productFamily: "oily_skin_cleanser",
    variant: "valid_foaming_match",
    title: "ClearKind Fragrance-Free Foaming Cleanser for Oily Skin",
    priceUsd: 20,
    features: [
      "Facial foaming cleanser formulated for oily and acne-prone skin.",
      "Fragrance-free, essential-oil-free, and non-comedogenic formula.",
      "Gentle daily cleansing with niacinamide and green tea.",
      "Budget-friendly price under $25.",
    ],
    details: { SkinType: ["Oily", "Acne-prone"], Form: "Foam", Fragrance: "Fragrance-free", VolumeMl: 150 },
    structuredAttributes: {
      item_type: "facial_cleanser",
      use_cases: ["daily_cleansing"],
      skin: { suitable_skin_types: ["oily", "acne_prone"], concerns: ["excess_oil", "blemishes"] },
      formula: { fragrance_free: true, non_comedogenic: true, texture: "foam" },
    },
  }),
  baseRecord({
    id: "DEMO-CLEANSER-COMEDOGENIC",
    categoryPath: ["Beauty & Personal Care", "Skin Care", "Face", "Cleansers"],
    catalogGroup: "cleanser",
    productFamily: "oily_skin_cleanser",
    variant: "missing_preferred_non_comedogenic",
    title: "ClearKind Fragrance-Free Oil Cleanser for Oily Skin",
    priceUsd: 19,
    features: [
      "Facial oil cleanser marketed for oily skin but not recommended for acne-prone skin.",
      "Fragrance-free formula, but not non-comedogenic and contains pore-clogging coconut oil.",
      "Suitable for occasional makeup removal rather than daily blemish care.",
      "Budget-friendly price under $25.",
    ],
    details: { SkinType: ["Oily", "Not acne-prone"], Form: "Oil", Fragrance: "Fragrance-free", VolumeMl: 150 },
    structuredAttributes: {
      item_type: "facial_cleanser",
      use_cases: ["makeup_removal"],
      skin: { suitable_skin_types: ["oily"], concerns: ["makeup_removal"], acne_prone_suitable: false },
      formula: { fragrance_free: true, non_comedogenic: false, texture: "oil" },
    },
  }),
  baseRecord({
    id: "DEMO-CLEANSER-BODY-WASH",
    categoryPath: ["Beauty & Personal Care", "Bath & Body", "Body Washes"],
    catalogGroup: "cleanser",
    productFamily: "oily_skin_cleanser",
    variant: "wrong_item_type_body_wash",
    title: "ClearKind Fragrance-Free Body Wash for Oily Skin",
    priceUsd: 15,
    features: [
      "Body wash for oily body skin; not a facial cleanser and not formulated for facial acne.",
      "Fragrance-free daily body formula.",
      "Non-comedogenic testing has not been performed for facial use.",
      "Budget-friendly price under $25.",
    ],
    details: { SkinType: ["Oily body skin"], Form: "Gel", Fragrance: "Fragrance-free", VolumeMl: 400 },
    structuredAttributes: {
      item_type: "body_wash",
      use_cases: ["body_cleansing"],
      skin: { suitable_skin_types: ["oily_body_skin"], concerns: ["body_oil"] },
      formula: { fragrance_free: true, non_comedogenic: null, texture: "gel" },
    },
  }),
  baseRecord({
    id: "DEMO-CLEANSER-TONER",
    categoryPath: ["Beauty & Personal Care", "Skin Care", "Face", "Toners"],
    catalogGroup: "toner_essence",
    productFamily: "oily_skin_cleanser",
    variant: "wrong_item_type_toner",
    title: "ClearKind Fragrance-Free Balancing Toner for Oily Skin",
    priceUsd: 17,
    features: [
      "Leave-on facial toner for oily and acne-prone skin; not a cleanser and does not wash the face.",
      "Fragrance-free and non-comedogenic formula.",
      "Contains niacinamide and green tea for post-cleansing use.",
      "Budget-friendly price under $25.",
    ],
    details: { SkinType: ["Oily", "Acne-prone"], Form: "Liquid toner", Fragrance: "Fragrance-free", VolumeMl: 150 },
    structuredAttributes: {
      item_type: "facial_toner",
      use_cases: ["post_cleansing_toner"],
      skin: { suitable_skin_types: ["oily", "acne_prone"], concerns: ["excess_oil", "blemishes"] },
      formula: { fragrance_free: true, non_comedogenic: true, texture: "liquid" },
      // This original retrieval near-miss doubles as an eligible companion fixture. Its explicit
      // role overrides the cleanser family's default test-only bundle metadata.
      bundling: {
        roles: ["post_cleanse_toner"],
        targets: ["lightweight_moisturizer"],
        compatibility_tags: ["oily", "acne_prone"],
        offer_eligible: true,
        priority: 100,
      },
    },
  }),
  baseRecord({
    id: "DEMO-MOISTURIZER-OILY",
    categoryPath: ["Beauty & Personal Care", "Skin Care", "Face", "Moisturizers"],
    catalogGroup: "moisturizer",
    productFamily: "oily_skin_moisturizer",
    variant: "complementary_add_on",
    title: "ClearKind Lightweight Gel Moisturizer for Oily Skin",
    priceUsd: 21,
    features: [
      "Lightweight fragrance-free gel moisturizer for oily and acne-prone skin.",
      "Non-comedogenic hydration with niacinamide and ceramides after cleansing or toner.",
      "Absorbs quickly without a greasy finish for everyday routine use.",
    ],
    details: { SkinType: ["Oily", "Acne-prone"], Form: "Gel", Fragrance: "Fragrance-free", VolumeMl: 60 },
    structuredAttributes: {
      item_type: "facial_moisturizer",
      use_cases: ["daily_moisturizing", "post_cleansing"],
      skin: { suitable_skin_types: ["oily", "acne_prone"], concerns: ["hydration", "barrier_support"] },
      formula: { fragrance_free: true, non_comedogenic: true, texture: "gel" },
    },
  }),
];

function csvEscape(value) {
  const text = typeof value === "string" ? value : JSON.stringify(value);
  return `"${text.replaceAll('"', '""')}"`;
}

function writeCategory(directory, fileStem, records) {
  const dataDir = path.join(ROOT_DIR, "data", directory);
  writeFileSync(path.join(dataDir, `${fileStem}.json`), `${JSON.stringify(records, null, 2)}\n`);

  const fields = [
    "id", "catalog_group", "product_family", "variant_key", "title", "brand_or_store",
    "price_usd", "average_rating", "rating_count", "image_url", "category_path", "features",
    "description", "details", "structured_attributes",
  ];
  const rows = [fields.join(",")];
  for (const record of records) {
    rows.push(fields.map((field) => csvEscape(record[field] ?? null)).join(","));
  }
  writeFileSync(path.join(dataDir, `${fileStem}.csv`), `${rows.join("\n")}\n`);

  const groupCounts = Object.fromEntries(
    [...new Set(records.map((record) => record.catalog_group))].map((group) => [
      group,
      records.filter((record) => record.catalog_group === group).length,
    ]),
  );
  writeFileSync(
    path.join(dataDir, "manifest.json"),
    `${JSON.stringify({
      source: "Synthetic demo fixtures",
      items: records.length,
      groups: groupCounts,
      product_families: [...new Set(records.map((record) => record.product_family))],
      schema_version: 1,
      notes: "Controlled near-neighbour variants for deterministic retrieval demonstrations. Clothing is maintained separately and untouched.",
    }, null, 2)}\n`,
  );
}

writeCategory("electronics", "electronics_catalog", electronics);
writeCategory("skincare", "skincare_catalog", skincare);
writeCategory("home-goods", "homegoods_catalog", []);

console.log(JSON.stringify({
  electronics: electronics.length,
  skincare: skincare.length,
  homeGoods: 0,
  nonClothingTotal: electronics.length + skincare.length,
  clothing: "unchanged",
}, null, 2));
